# single application_id is allocated to all servers

state_type: baseline
application_id: 0
instance:
  instance_type: Splitwise
  max_batch_size: 512
  max_batch_tokens: 2048
  max_preemptions: 4
  pipeline_parallelism: 1
  tensor_parallelism: 8
